apiVersion: apps/v1
kind: Deployment
metadata:
  name: gifmachine
spec:
  selector:
    matchLabels:
      app: gifmachine
  template:
    metadata:
      labels:
        app: gifmachine
    spec:
      initContainers:
        - name: setup-db
          image: ghcr.io/moser-ss/gifmachine
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-gifmachine-secret
                  key: db-password
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-gifmachine-config
                  key: db-user
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: db-gifmachine-config
                  key: db-hostname
            - name: RACK_ENV
              value: production

          command:
            - bundle
          args:
            - exec
            - rake
            - db:migrate

      containers:
        - name: gifmachine
          image: ghcr.io/moser-ss/gifmachine
          imagePullPolicy: Always
          env:
            - name: GIFMACHINE_PASSWORD
              value: foo
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-gifmachine-secret
                  key: db-password
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-gifmachine-config
                  key: db-user
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: db-gifmachine-config
                  key: db-hostname
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOSTNAME):5432/gifmachine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: main
              containerPort: 4567
          livenessProbe:
            httpGet:
              path: /gif
              port: 4567
          readinessProbe:
            httpGet:
              path: /gif
              port: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: gifmachine
spec:
  selector:
    app: gifmachine
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: main
              
              
              
