development:
  adapter: postgresql
  database: gifmachine
  host: localhost
  user: gifmachine
  password: developer1
container:
  adapter: postgresql
  database: gifmachine
  host: db
  user: gifmachine
  password: developer1
