development:
  adapter: postgresql
  database: gifmachine
  host: localhost
  user: gifmachine
  password: developer1
container:
  adapter: postgresql
  database: gifmachine
  host: db
  user: gifmachine
  password: developer1
production:
  adapter: postgresql
  database: gifmachine
  host: <%= ENV['DB_HOSTNAME'] %>
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
